### ISSUE TITLE
Some leds of the strip stop giving lights

### ISSUE THREAD

**Issue by Michelvl92** [corbanmailloux/esp-mqtt-rgb-led#15]
I am using your project on my nodemcu and like the nice fade between different brightnesses and colors.
But if a specific color an brightness is set, then after some time; 20 min and sometimes 1 hour, some leds of the ledstrip stop giving light. Mostly at the beginning of the strip. If i the update the light color or brightness the all the leds of the strip are shining. I am using an resistor at the Din of the led, and a 1000uf capacitor at the 5V source. I am also running other code like arduino OTA and a task for the temperature sensor. What do you think could be wrong? And have you maybe an idea what could be wrong?

**Comment by corbanmailloux** [comment]
Hey, @Michelvl92. What kind of LEDs are you using? With a standard analog LED strip, all of the LEDs should be at the same brightness and color (unless you aren't supplying enough current). 
Based on your message, it sounds like you are using digital LEDs, which have a digital-in pin and generally run at 5 volts.

If you are using digital LEDs, I have no idea what would be causing the issue. I'd suggest checking your power supply (although usually, that will cause dimming at the end of the strip, not the beginning) and look into the documentation for whatever LED library you are using.

As this is a highly modified version of this project, I don't know what help I can offer. Let me know if there is more guidance I can provide.
