### ISSUE TITLE
Resistors used?

### ISSUE THREAD

**Issue by donnib** [corbanmailloux/esp-mqtt-rgb-led#22]
Hi,
What valuw resistors did you use, also the FET type. If you have the schematics that would be cool to see.

**Comment by corbanmailloux** [comment]
Hi @donnib. I used 10k ohm resistors (brown-black-orange, from the schematic in the README).
The specific MOSFETs I use are [these ones from SparkFun](https://www.sparkfun.com/products/10213), but any N-channel MOSFETs that handle the voltage should be fine.
