### ISSUE TITLE
Home Assistant MQTT JSON light change

### ISSUE THREAD

**Issue by pjmsullivan** [corbanmailloux/esp-mqtt-rgb-led#51]
I think HA 0.84 introduced a breaking change for mqtt json lights:
from:
platform: mqtt_json

to:
platform: mqtt
schema: json

I'm sure you already know, but just a tip for other folks.

Thanks for this awesome project!

**Comment by corbanmailloux** [comment]
Thanks for the reminder! I'll update the readme accordingly.
