### ISSUE TITLE
RGBW ledstrip connection

### ISSUE THREAD

**Issue by lodv** [corbanmailloux/esp-mqtt-rgb-led#62]
Hi,
I have a question concerning this tutorial: ESP8266 MQTT RGB(W) Lights Using JSON for Home Assistant.
I use a RGBW led strip. It has 5 wires: RGB Black and white.
My led strip has separate led for white.
In your image I can't see the connection for the black wire and the white wire goes to the +12V.
Please can you describe what I have to change in order to get it working.
Thank you in advance.
Kind regards,
Yvonne

**Comment by corbanmailloux** [comment]
If you're using an RGBW strip, you'll need an additional MOSFET and wiring. You should connect the wire for the white LEDs through a MOSFET to an additional GPIO pin on the ESP, and set the `CONFIG_PIN_WHITE` value to that pin: https://github.com/corbanmailloux/esp-mqtt-rgb-led/blob/master/mqtt_esp8266_light/config-sample.h#L25.

Additionally, GitHub issues aren't really meant for support, so I'm closing this issue.
