### ISSUE TITLE
Mosfet

### ISSUE THREAD

**Issue by ghost** [corbanmailloux/esp-mqtt-rgb-led#8]
Which mosfet to use ?

IRF840N Mosfet?

**Comment by corbanmailloux** [comment]
I specifically use these ones: https://www.sparkfun.com/products/10213
because I have several around, but any properly-rated N-channel MOSFET
should do.

**Comment by ghost** [comment]
The resistors 1k ?

**Comment by corbanmailloux** [comment]
I think I'm using 10k, but it shouldn't matter too much. They are just pull-ups to keep the MOSFET from floating.

**Comment by ghost** [comment]
Thank you very much I will check this project with IRF840N and let you know the result. Have a good day.
